### ISSUE TITLE
genmap borked

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/caac-map#63]
```
$ ./genmap.py output/topics.json 
Traceback (most recent call last):
  File "./genmap.py", line 501, in <module>
    magnitudes = {name: xrec(rec) for name, rec in blocks.items()}
  File "./genmap.py", line 501, in <dictcomp>
    magnitudes = {name: xrec(rec) for name, rec in blocks.items()}
  File "./genmap.py", line 500, in <lambda>
    xrec = lambda rec: [(rec['uid'], int(rec['duration'])) for rec in rec.values()]
TypeError: string indices must be integers
$
```

**Comment by chadwhitacre** [comment]
Need to catch it up with the changes to `topics.json` in https://github.com/saxifrage/caac-map/pull/58 and possibly https://github.com/saxifrage/caac-map/pull/53.
